"""'增加post表的存储大小为1000'

Revision ID: 138e29e1dbf1
Revises: aadd474c049b
Create Date: 2021-01-09 09:18:14.423951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '138e29e1dbf1'
down_revision = 'aadd474c049b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'body')
    # ### end Alembic commands ###
