"""'增加post表的存储大小为1000'

Revision ID: aadd474c049b
Revises: ead4e7a3402a
Create Date: 2021-01-09 09:16:42.615094

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aadd474c049b'
down_revision = 'ead4e7a3402a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body', mysql.VARCHAR(length=140), nullable=True))
    # ### end Alembic commands ###
